### ISSUE TITLE
Dragging the scroll bar to scroll does not work.

### ISSUE THREAD

**Issue by spivurno** [robinparisi/tingle#139]
### Summary

Clicking and dragging the scrollbar to scroll through a modal that is taller than the viewport does not work. Interestingly, scrolling via a scroll wheel or trackpad does work.

### Steps to Recreate

1. Open https://tingle.robinparisi.com/
2. Click the "Big Content? No problem!" demo button.
3. Ensure that your browser window is smaller than the modal so that scrolling is required.
4. Attempt to click and drag the scrollbar. The result differs depending on OS and browser. Here are the results from my testing.

Mac | Firefox: Clicking the scrollbar closes the modal.
Mac | Chrome: Clicking the scrollbar closes the modal.
Mac | Safari: Clicking the scrollbar closes the modal.

The following were tested with BrowserStack:

Windows | Firefox: Works!
Windows | Chrome: The scrollbar does not move.
Windows | Safari: Couldn't get the site to load...
Windows | IE11: Works!
Windows | Edge: The scrollbar does not move.

---

Eager to be helpful. I'd be happy to commission or provide some additional sponsorship for your attention to this issue. I really appreciate your time!

**Comment by emmanuelballery** [comment]
Hello,

The rule `.tingle-modal:before` used to add a backdrop filter `blur` is in a `fixed` position and is rendered in front of the scrollbar ;

https://github.com/robinparisi/tingle/blob/4e4237a49858667cecbf570374016e66b64f9b21/src/tingle.css#L248-L262

This is only the case when `backdrop-filter` [is supported](https://caniuse.com/#search=backdrop-filter) hence the strange browsers behaviors.

I think you can use an `absolute` positioning instead of a `fixed` one to avoid this bug (as its parent is already `fixed`) :

```css
@supports (backdrop-filter: blur(12px)) {
  .tingle-modal:before {
    position: absolute;
  }
}
```

**Comment by spivurno** [comment]
Hi @emmanuelballery, thank you! This solves the issue in both Windows Chrome and Windows Edge.

Do you have any insights into how this might be addressed in the Mac browsers? I tried your fix there without success. I tried disabling the ::before backdrop completely. Still no love. I suspect the issue may have to do with the click event being picked up by Tingle.

**Comment by emmanuelballery** [comment]
Hello,

This is the list of browsers I worked with :

- [**no bug**] do not support `backdrop-filter` :
  - Linux > Chrome 73.0.3683.86
  - Linux > Firefox 75.0
  - Windows (VM) > Firefox 75.0
  - Windows (VM) > IE 11.615.17763.0
  - Mac (VM) > Firefox 75.0

- [**bug**] support `backdrop-filter`, scrollbar is not accessible :
  - Windows (VM) > Chrome 81.0.4044.113
  - Windows (VM) > Edge 44.17763.1.0
  - Windows (VM) > Opera 67.0.3575.137
  - Mac (VM) > Chrome 81.0.4044.113
  - Mac (VM) > Safari 11.0

---

1. Applying `absolute` positioning instead of a `fixed` one to `.tingle-modal:before` is not a solution (sorry), it will limit the size of the backdrop ; when scrolling it's noticible ; `display: none;` is the solution for now ; 

![Capture du 2020-04-21 09-47-54](https://user-images.githubusercontent.com/1687685/79841122-3f271080-83b7-11ea-921c-e407c7ff431c.jpg)

2. In Safari the scrollbar is not rendering, even when preference is set to always :

![Capture du 2020-04-21 10-08-10](https://user-images.githubusercontent.com/1687685/79842792-9b8b2f80-83b9-11ea-96a0-42b3a132c2c5.jpg)

I tried to hack the scrollbar using this StackOverflow answer : https://stackoverflow.com/a/7855592

```css
.tingle-modal::-webkit-scrollbar {
  -webkit-appearance: none;
}
.tingle-modal::-webkit-scrollbar:vertical {
  width: 10px;
}
.tingle-modal::-webkit-scrollbar-thumb {
  border: 2px solid white;
  background-color: black;
}
.tingle-modal::-webkit-scrollbar-track {
  background-color: #ffffff;
}
```

It works. It is usable. But, what a hack ...

![Capture du 2020-04-21 10-21-49](https://user-images.githubusercontent.com/1687685/79843186-3552dc80-83ba-11ea-929e-f26705129f90.jpg)

---

I don't think I can do more. A new DOM node to handle this `blur` backdrop would probably be the best solution.

**Comment by robinparisi** [comment]
It's a tricky one...

We should be able to calculate scrollbar width then adapt event listener to handle click on scrollbar by using this:

```js
var scrollbarWidth = this.modal.offsetWidth - this.modal.clientWidth
```

But on MacOS, depending on the setting shown by @emmanuelballery, the browser won't return the correct size when the scrollbar is set to "When scrolling" or when using Safari.

We could use this data as a workaround but I find it a bit hacky:

https://codepen.io/sambible/post/browser-scrollbar-widths

To be honest, I don't understand why scrollbar trigger click event. It should be a different DOM elem or trigger a different event...

**Comment by emmanuelballery** [comment]
Hi @robinparisi,

The real problem is this rule `.tingle-modal:before` which displays an invisible block in front of the scrollbar (a fixed block in a fixed block). The `click` event is not triggered by the scrollbar, but by the `:before` rendered in front of it. Hiding/removing this `:before` fixes everything;

This issue started here 21e333cffcc307515baf544b26c4a73218d6b5b0.

The blur effect is fine when using the `tingle-content-wrapper` class as written in the doc:

> Important: For the blur effect, you need to wrap your content inside a container with the "tingle-content-wrapper" class.

**Comment by emmanuelballery** [comment]
A solution could be to add a parent to `.tingle-modal` with this blur effet. Something like:

```scss
.tingle-modal-backdrop {
  position: fixed;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  backdrop-filter: blur(18px);
  & > .tingle-modal {
    position: relative;
    height: 100%;
    overflow-y: auto;
    // remove top, right, bottom, left, z-index rules
  }
}
```
