### ISSUE TITLE
Cannot select the texts in the modal

### ISSUE THREAD

**Issue by ayaka14732** [robinparisi/tingle#148]
I would like to create a modal with the texts in it selectable and copyable for users.

**Comment by emmanuelballery** [comment]
Hi @ayaka14732!

There is a CSS rule :

```css
.tingle-modal {
  -webkit-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

Change its value for :

```css
.tingle-modal {
  -ms-user-select: text;
  -webkit-user-select: text;
  user-select: text;
}
```
