### ISSUE TITLE
Full screen support

### ISSUE THREAD

**Issue by fredericoregateiro** [robinparisi/tingle#71]
Is there an option to set the window as full screen?
like: width: 100%; height: 100%;

Thanks,
Frederico

**Comment by pacMakaveli** [comment]
You can create a new TingleModal class: 

```css
.tingle-modal.tingle-modal--fullscreen .tingle-modal-box {
  width: 100%; 
  height: 100%;
}
```

And then use the said class:

```js
const modal = new TingleModal.modal({
  closeMethods: ['overlay', 'button', 'escape'],
  closeLabel: "Close",
  cssClass: ['tingle-modal--fullscreen'],
  onOpen: () => { },
  beforeClose: () => {
    return true;
  },
  onClose: () => {
    modal.destroy()
  }
});
```
